version: "3"

services:
  app:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app
    networks:
      - app-network
    depends_on:
      - mysql
    ports:
      - "9090"
    volumes:
      - ./logs:/logs

  nginx:
    build:
      context: .
      dockerfile: "./build/nginx/Dockerfile"
    container_name: nginx
    networks:
      - app-network
    depends_on:
      - app
    ports:
      - "90:90"
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./remove_cache.sh:/remove_cache.sh

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    networks:
      - app-network
    ports:
      - "3309:3309"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    networks:
      - app-network
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge